# Generated by Django 4.0.1 on 2022-05-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_rename_content_notice_content1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='content1',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='subject1',
            new_name='subject',
        ),
    ]
