# Generated by Django 4.0.4 on 2022-05-26 06:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_product_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='review',
        ),
    ]
