# Generated by Django 4.0.1 on 2022-05-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_answer_alter_question_create_date_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
    ]
