# Generated by Django 4.0.1 on 2022-05-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
