# Generated by Django 4.0.1 on 2022-05-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='subject',
            new_name='subject1',
        ),
    ]
