# Generated by Django 4.0.1 on 2022-05-11 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_rename_content1_notice_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.question')),
                ('voter', models.ManyToManyField(related_name='voter_answer2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
