# Generated by Django 4.0.1 on 2022-05-28 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_alter_n_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n_comment',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.notice'),
        ),
    ]
